package com.zj.api.exception

import retrofit2.HttpException


/**
 * @param id is generated by default,customized by using the [com.zj.api.eh.ApiHandler] annotation，@see [com.zj.api.eh.ApiHandler.id] to learn how to use.
 *
 * @param httpException Exception for an unexpected, non-2xx HTTP response.
 *
 * @param case It always coexists with [httpException], some errors are non-HttpException,
 * I have generated a unified HttpException based on it,
 * but for better extensibility (such as implementing a custom CallAdapterFactory and need to throw an exception for easy identification when using case),
 * it will work better than HttpException.
 * */
@Suppress("unused")
class ApiException(val id: String, val httpException: HttpException?, case: Throwable?) : Throwable(case)